### ISSUE TITLE
redmi note 11 pro plus 5g

### ISSUE THREAD

**Issue by Hamood111** [pissarro-dev/OTA#1]
hello sir sorry for talking here maybe it's not the right place I'm just wondering is this rom for redmi note 11 pro plus 5g Pissarro or not and do I need to twrp or not cuz I don't have twrp and there's one on unofficial twrp website for my phone but unfortunately is not working I hope to answer my question soon thanks

**Comment by rio004** [comment]
The boot.img has LineageOS recovery which you flash the ROM and Gapps if you want.

**Comment by Hamood111** [comment]
> The boot.img has LineageOS recovery which you flash the ROM and Gapps if you want.

I see thank u so much sir I was just wondering cuz I think there's more than one Pissarro phone Redmi Note 11 Pro/Pro+/Redmi Note 11 Pro+ 5G/Xiaomi 11i 5G/Hypercharge I just wanna make sure it's working with mine mi 11 pro+ 5g Pissarro but the way u answered without talking about means it's working for my phone thank u Sir I'm really sorry for any trouble I'm really happy cuz finally some programmer cares about us I hope to made more roms and kernels and I will try as much I could to support u thanks again bye
