### ISSUE TITLE
Speaker noice issue

### ISSUE THREAD

**Issue by jieran233** [pissarro-dev/OTA#3]
I also noticed another issue, but I'm not sure if it's caused by this ROM, even though I have never faced that issue before using MIUI on this phone, your feedback is crucial:

sometimes there is a white noise in the left channel of the speaker and wired headphones (In a quiet environment, you can clearly hear it at the left channel of the speaker by putting your ear close to it)

For example, **it is noticeable on the lock screen when the screen lights up**, or during the playback of any audio
(especially quieter music in low volume, and the notification sound when inserting or removing the charging cable)

**Sorry if this issue is not caused by this ROM.**

<details>
<summary>中文</summary>

我还注意到另一个问题，但我不确定它是否由此ROM引起，即使我从未在之前在这部手机上使用MIUI时遇到过该问题，各位的反馈至关重要：

有时扬声器和有线耳机的左声道中会出现白噪音（在安静的环境中将耳朵靠近扬声器的左声道可以清楚听到）

例如，**点亮屏幕在锁定屏幕**，或在任何音频播放期间（尤其是低音量的安静音乐以及插拔充电线时的提示音）

**如果问题不是由这个ROM导致的，我很抱歉。**

</details>

_Originally posted by @jieran233 in https://github.com/pissarro-dev/OTA/issues/2#issuecomment-1878098964_

**Comment by rio004** [comment]
Could you test latest release and let me know if this issue still has to be left open?

**Comment by jieran233** [comment]
> Could you test latest release and let me know if this issue still has to be left open?

Of course, if I can keep the data to upgrade perfectly. Can you tell me how to upgrade while preserving my data?
Also, a bit too much to ask, could you please tell me how to compile KernelSU for this ROM's kernel?
I'm sorry for asking so many boring basic questions, but I don't have enough basic knowledge about custom ROMs, and finding useful guides on this topic on search engines is difficult. I would really appreciate any reply. , I'm sorry to cause you a series of troubles on such a simple question, I will learn as much as possible anyway. I know how much developers hate newbie questions in issues, so I'm very sorry, but even so I hope to be able to accept your help and help you.
So my answer is, I'm very sorry, at least right now I'm not qualified enough to help you, but anyway I really like what you and your team have developed

**Comment by rio004** [comment]
I have already built with KSU with that kernel, which could be found here: https://www.pling.com/p/2119905/

**Comment by jieran233** [comment]
I did this, but it just stuck on the first logo screen. Did I do something wrong? what do I do?

```shell
# fastboot flash boot boot.img
Sending 'boot_b' (131072 KB)                       OKAY [  4.468s]
Writing 'boot_b'                                   OKAY [  0.316s]
Finished. Total time: 4.786s
# fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.201s
# adb sideload lineage-20.0-20240110-UNOFFICIAL-pissarro.zip 
serving: 'lineage-20.0-20240110-UNOFFICIAL-pissarro.zip'  (~47%)    adb: failed to read command: Success
# adb sideload HydrogenKernel-KSU-pissarro-20240110-2238.zip 
Total xfer: 1.00x                                                       
```

**Comment by jieran233** [comment]
> I have already built with KSU with that kernel, which could be found here: https://www.pling.com/p/2119905/

I flash the newer ROM and it can boot, but when I flash this Kernel `HydrogenKernel-KSU-pissarro-20240110-2238.zip`, it just stuck on first logo screen.

I did this:
```shell
fastboot flash boot boot.img
# then reboot to recovery, apply update from adb sideload
adb sideload lineage-20.0-20240110-UNOFFICIAL-pissarro.zip
# choose yes to reboot to recovery now
adb sideload HydrogenKernel-KSU-pissarro-20240110-2238.zip
```

**Comment by jieran233** [comment]
This issue should have been fixed. Thank you and your team for your hard work
